version: '3.4'

services:
  liquidsoap:
    build:
      context: .
    image: xtradio-liquidsoap
    container_name: liquidsoap
    network_mode: host
    ports:
      - "8089:8089"
      - "1234:1234"
      - "8082:8082"
    volumes:
      - /home/akos/Music/xtradio/MUSIC:/MUSIC
      - /home/akos/Dev/playlist-generate/playlist.txt:/playlist.txt
        #links: 
        #- icecast
    environment: 
      - DJ_PASSWORD=test
      - ICECAST_HOST=localhost
      - ICECAST_PASSWORD=test
      - API_HOST=localhost:10000
  icecast:
    image: luzifer/icecast2:latest
    container_name: icecast
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - ./icecast.xml:/config/icecast.xml

